# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aulys',
                'doc_host': 'https://nguyenbaanh7779.github.io',
                'git_url': 'https://github.com/nguyenbaanh7779/aulys',
                'lib_path': 'aulys'},
  'syms': {'aulys.core': {'aulys.core.foo': ('core.html#foo', 'aulys/core.py')}}}
