# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_stast_fea.ipynb.

# %% auto 0
__all__ = ['stast_fea', 'overview_table', 'plot_univariate', 'plot_multivariate']

# %% ../nbs/01_stast_fea.ipynb 5
import os
import sys

import yaml
import pandas as pd
import lets_plot as lp
from IPython.display import Markdown

sys.path.insert(1, os.getcwd())

import config
import src.utils as utils
import src.chart as chart
import src.data as data

# %% ../nbs/01_stast_fea.ipynb 7
def stast_fea(df, idx_col, cat_cols, num_cols):
    """
    Tổng hợp các đặc trưng dạng số bằng các phép thống kê:
    - Đối với dữ liệu numerical:
        * Trung bình (`mean`)
        * Giá trị lớn nhất (`max`)
        * Giá trị nhỏ nhất (`min`)
        * Tổng (`sum`)
        * Trung vị (`median`)
        * Hiệu số giữa max và min (`diff`)
    - Đối với categorical:
        * Số lượng giá trị khác nhau (`nunique`)
        * Giá trị xuất hiện nhiều nhất (`mode`)
        * Tần suất xuất hiện của từng giá trị trong cột phân loại
    
    Args:
        df (pd.DataFrame): Dữ liệu đầu vào
        idx_col (str): Cột index (ID nhóm)
        num_cols (list): Danh sách các cột số để tổng hợp
        cat_cols (list): Danh sách các cột phân loại để tổng hợp

    Returns:
        pd.DataFrame: DataFrame chứa các feature tổng hợp
    """
    return data.agg_fea(
        df=df, idx_col=idx_col, cat_cols=cat_cols, num_cols=num_cols
    )

# %% ../nbs/01_stast_fea.ipynb 11
def overview_table(df):
    """
    Tạo bảng tổng quan về dữ liệu, bao gồm:
    - Số lượng giá trị trùng lặp (`Count_duplicate`)
    - Số lượng giá trị bị thiếu (`Count_missing`)
    - Tỷ lệ phần trăm giá trị bị thiếu (`Percent_missing`)
    - Số lượng giá trị duy nhất (`Count_distinct`)
    - Số lượng giá trị bằng 0 (`Count_zero`, chỉ áp dụng cho kiểu số)
    - Tỷ lệ phần trăm giá trị bằng 0 (`Percent_zero`, chỉ áp dụng cho kiểu số)
    
    Args:
        df (pd.DataFrame, optional): DataFrame đầu vào.
    
    Returns:
        pd.DataFrame: DataFrame chứa thông tin tổng quan về các cột.
    """
    return utils.overview_table(df=df)

# %% ../nbs/01_stast_fea.ipynb 14
def plot_univariate(df, bin_cols):
    """
    Vẽ biểu đồ đơn biến (univariate) cho tất cả các cột trong DataFrame.

    - Nếu là cột phân loại (chuỗi): vẽ biểu đồ tần suất.
    - Nếu là cột số: chia bin rồi vẽ biểu đồ.

    Args:
        df (pd.DataFrame): Dữ liệu đầu vào (cột đầu tiên thường là ID, sẽ bỏ qua).
        bin_cols (dict): Từ điển chứa các giá trị phân bin cho các cột số.
    """
    display(chart.plot_univariate(df=df, bin_cols=bin_cols))

# %% ../nbs/01_stast_fea.ipynb 18
def plot_multivariate(df, column, bin_cols):
    """
    Vẽ biểu đồ phân tích đa biến giữa một cột chính (`column`) với tất cả các cột còn lại.
    Tùy vào kiểu dữ liệu (chuỗi hoặc số), cột được chia bin hoặc chuyển thành chuỗi để trực quan hóa.

    Args:
        df (pd.DataFrame): Dữ liệu đầu vào.
        column (str): Cột chính cần phân tích.
        bin_cols (dict): Dictionary chứa thông tin bin cho các cột số.

    Returns:
        None: Hiển thị biểu đồ crosstab cho từng cặp biến.
    """
    display(chart.plot_multivariate(df=df, column=column, bin_cols=bin_cols))
